# Generated by Django 4.0 on 2023-04-27 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(default=10)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('texto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaSalida', models.TimeField()),
                ('horaLlegada', models.TimeField()),
                ('precioPrimera', models.IntegerField()),
                ('precioEconomica', models.IntegerField()),
                ('precioPrimeraDesc', models.IntegerField()),
                ('precioEconomicaDesc', models.IntegerField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='todo.ciudad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origenes', to='todo.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('saldo', models.IntegerField(default=0)),
                ('fechaNaci', models.DateField()),
                ('lugarNaci', models.CharField(max_length=50)),
                ('dirFact', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('N', 'No Responde')], default='N', max_length=20)),
                ('tipoUsuario', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePasajero', models.CharField(max_length=50)),
                ('emailPasajero', models.EmailField(max_length=254)),
                ('edadPasajero', models.IntegerField()),
                ('asiento', models.CharField(max_length=4)),
                ('clase', models.CharField(choices=[('p', 'Primera Clase'), ('e', 'Clase Economica')], max_length=20)),
                ('EstadoCheckIn', models.CharField(default='No Realizado', max_length=15)),
                ('Compraid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compraid', to='todo.compra')),
                ('Vueloid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vueloid', to='todo.vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('d', 'debito'), ('c', 'credito')], max_length=20)),
                ('disponible', models.IntegerField(default=200000)),
                ('numero', models.CharField(max_length=16)),
                ('nombre', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('vencimiento', models.DateField()),
                ('clienteid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.usuario')),
            ],
        ),
    ]
