# Generated by Django 4.1.7 on 2023-05-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='fechaSalida',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
