# Generated by Django 4.1.7 on 2023-05-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='asientos_economica',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='compra',
            name='asientos_primera',
            field=models.IntegerField(default=10),
        ),
    ]
