# Generated by Django 4.1.7 on 2023-05-23 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('todo', '0002_alter_customuser_lugarnaci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='destino',
            field=models.ForeignKey(limit_choices_to={'name__in': ['Pereira', 'Bogotá', 'Medellín']}, on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='origen',
            field=models.ForeignKey(limit_choices_to={'name__in': ['Pereira', 'Bogotá', 'Medellín']}, on_delete=django.db.models.deletion.CASCADE, related_name='origenes', to='cities_light.city'),
        ),
    ]
