# Generated by Django 4.1.7 on 2023-05-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_compra_asientos_economica_compra_asientos_primera'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='asientos_fila',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='filas',
            field=models.IntegerField(default=0),
        ),
    ]
