# Generated by Django 4.1.7 on 2023-05-24 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_vuelo_fechasalida'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='horaSalida',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
