# Generated by Django 4.1.7 on 2023-05-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_vuelo_destino_alter_vuelo_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='codigo',
            field=models.TextField(null=True, unique=True),
        ),
    ]
