# Generated by Django 3.2.6 on 2023-04-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_compras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('saldo', models.IntegerField()),
                ('fechaNaci', models.DateField()),
                ('lugarNaci', models.CharField(max_length=50)),
                ('dirFact', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('tipoUsuario', models.CharField(max_length=20)),
            ],
        ),
    ]
