# Generated by Django 4.1.7 on 2023-05-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_vuelo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='codigo',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
