# Generated by Django 4.1.7 on 2023-05-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(default='sin_selec', max_length=16, null=True),
        ),
    ]
