# Generated by Django 4.1.7 on 2023-05-24 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_vuelo_minutosalida_alter_vuelo_horasalida'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='fechaLlegada',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='horaLlegada',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='minutoLlegada',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
    ]
