# Generated by Django 4.1.7 on 2023-05-24 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_vuelo_fechallegada_vuelo_horallegada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='tiempoVuelo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='precioEconomicaDesc',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='precioPrimeraDesc',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
