# Generated by Django 4.1.7 on 2023-05-26 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_compra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.seat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='edadPasajero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='emailPasajero',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nombrePasajero',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
