# Generated by Django 3.2.6 on 2023-04-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_vuelos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vuelos',
        ),
    ]
