# Generated by Django 4.1.7 on 2023-05-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_vuelo_tiempovuelo_alter_vuelo_precioeconomicadesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='destino',
            field=models.CharField(choices=[('Pereira', 'Pereira'), ('Bogotá', 'Bogotá'), ('Medellín', 'Medellín'), ('Cali', 'Cali'), ('Cartagena', 'Cartagena'), ('Madrid', 'Madrid'), ('Londres', 'Londres'), ('New York', 'New York'), ('Buenos Aires', 'Buenos Aires'), ('Miami', 'Miami')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='origen',
            field=models.CharField(choices=[('Pereira', 'Pereira'), ('Bogotá', 'Bogotá'), ('Medellín', 'Medellín'), ('Cali', 'Cali'), ('Cartagena', 'Cartagena'), ('Madrid', 'Madrid'), ('Londres', 'Londres'), ('New York', 'New York'), ('Buenos Aires', 'Buenos Aires'), ('Miami', 'Miami')], max_length=100),
        ),
    ]
