# Generated by Django 3.2.6 on 2023-04-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_delete_vuelos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaSalida', models.TimeField()),
                ('horaLlegada', models.TimeField()),
                ('precioPrimera', models.IntegerField()),
                ('precioEconomica', models.IntegerField()),
                ('precioPrimeraDesc', models.IntegerField()),
                ('precioEconomicaDesc', models.IntegerField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='todo.ciudades')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origenes', to='todo.ciudades')),
            ],
        ),
    ]
