# Generated by Django 4.2 on 2023-05-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_ticket_asiento_alter_ticket_edadpasajero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('N', 'No Responde')], default='N', max_length=20),
        ),
    ]
