# Generated by Django 3.2.6 on 2023-04-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_vuelos'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='precio',
            field=models.IntegerField(default=10),
        ),
    ]
