# Generated by Django 3.2.6 on 2023-04-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_compras_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
