# Generated by Django 3.2.6 on 2023-04-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_compras_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('texto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('d', 'debito'), ('c', 'credito')], max_length=20)),
                ('disponible', models.IntegerField(default=200000)),
                ('numero', models.CharField(max_length=16)),
                ('nombre', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('saldo', models.IntegerField()),
                ('fechaNaci', models.DateField()),
                ('lugarNaci', models.CharField(max_length=50)),
                ('dirFact', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('N', 'No Responde')], default='N', max_length=20)),
                ('tipoUsuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Ciudades',
            new_name='Ciudad',
        ),
        migrations.RenameModel(
            old_name='Compras',
            new_name='Compra',
        ),
        migrations.RenameModel(
            old_name='Vuelos',
            new_name='Vuelo',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='clienteid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.usuario'),
        ),
    ]
