# Generated by Django 3.2.6 on 2023-04-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20230424_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePasajero', models.CharField(max_length=50)),
                ('emailPasajero', models.EmailField(max_length=254)),
                ('edadPasajero', models.IntegerField()),
                ('asiento', models.CharField(max_length=4)),
                ('clase', models.CharField(choices=[('p', 'Primera Clase'), ('e', 'Clase Economica')], max_length=20)),
                ('EstadoCheckIn', models.CharField(default='No Realizado', max_length=15)),
                ('Compraid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compraid', to='todo.compra')),
                ('Vueloid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vueloid', to='todo.vuelo')),
            ],
        ),
    ]
