# Generated by Django 3.2.6 on 2023-04-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
