# Generated by Django 4.2.1 on 2023-05-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo',
            field=models.CharField(choices=[('d', 'debito'), ('c', 'credito')], max_length=16),
        ),
    ]
